---

- name: Verify
  hosts: all
  become: true
  vars:
    aptly_repo_name: debian-local
    aptly_distribution_name: xenial
    nginx_sites_enabled:
      - aptly.conf
    nginx_sites:
      - tests/templates/nginx/aptly.conf.j2

  roles:
    - nginx

  post_tasks:

    - name: Install test dependencies
      apt:
        name: python-httplib2

    - name: Test version
      uri:
        url: "http://localhost/api/version"

    - name: Copy dummy package
      copy:
        src: "{{ item }}"
        dest: /tmp
        owner: root
        group: root
        mode: 0644
      with_items:
        - tests/files/dummy_0.1_all.deb
        - tests/files/sigh_1607.1.6-1_amd64.deb

    - name: Upload dummy package to server
      command: curl -X POST -F file=@/tmp/dummy_0.1_all.deb http://localhost/api/files/dummy

    - name: Add dummy package to repository
      uri:
        url: "http://localhost/api/repos/{{ aptly_repo_name }}/file/dummy"
        method: POST

    - name: Update repository
      uri:
        url: "http://localhost/api/publish/filesystem:web:{{ aptly_repo_name }}/{{ aptly_distribution_name }}"
        method: PUT
        body: "{}"
        headers:
          Content-Type: "application/json"

    - name: Add the local repo key
      apt_key:
        file: "/var/lib/aptly/public/public.key"
        state: present

    - name: Add and remove APT repositories
      apt_repository:
        filename: "{{ aptly_repo_name }}.list"
        repo: "deb http://localhost/{{ aptly_repo_name }} {{ aptly_distribution_name }} main"
        update_cache: true
        state: present

    - name: Install dummy
      package:
        name: dummy
        state: present

    - name: Upload sigh package to server
      command: curl -X POST -F file=@/tmp/sigh_1607.1.6-1_amd64.deb http://localhost/api/files/sigh

    - name: Add sigh package to repository
      uri:
        url: "http://localhost/api/repos/{{ aptly_repo_name }}/file/sigh"
        method: POST

    - name: Update repository
      uri:
        url: "http://localhost/api/publish/filesystem:web:{{ aptly_repo_name }}/{{ aptly_distribution_name }}"
        method: PUT
        body: "{}"
        headers:
          Content-Type: "application/json"

    - name: Install sigh
      apt:
        name: sigh
        update_cache: true
        state: present

- name: Verify
  hosts: all
  become: true
  vars:
    goss_version: v0.3.2
    goss_arch: amd64
    goss_dst: /usr/local/bin/goss
    goss_sha256sum: 2f6727375db2ea0f81bee36e2c5be78ab5ab8d5981f632f761b25e4003e190ec
    goss_url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
    goss_test_directory: /tmp
    goss_format: documentation
  tasks:
    - name: Download and install Goss
      get_url:
        url: "{{ goss_url }}"
        dest: "{{ goss_dst }}"
        sha256sum: "{{ goss_sha256sum }}"
        mode: 0755

    - name: Copy Goss tests to remote
      copy:
        src: "{{ item }}"
        dest: "{{ goss_test_directory }}/{{ item | basename }}"
      with_fileglob:
        - "{{ playbook_dir }}/tests/test_*.yml"

    - name: Register test files
      shell: "ls {{ goss_test_directory }}/test_*.yml"
      register: test_files

    - name: Execute Goss tests
      command: "{{ goss_dst }} -g {{ item }} validate --format {{ goss_format }}"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"

    - name: Display details about the goss results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Goss failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
